In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

2.2.3

In [3]:
df=pd.read_csv('Walmart dataset.csv')

In [4]:
df.shape

(10051, 11)

In [5]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05-01-2019,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08-03-2019,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03-03-2019,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27-01-2019,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08-02-2019,10:37:00,Ewallet,5.3,0.48

In [6]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [8]:
#Duplicated

df.duplicated().sum()

np.int64(51)

In [9]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [10]:
#Drop Duplicated

df.drop_duplicates(inplace=True)
#verify
df.duplicated().sum()

np.int64(0)

In [11]:
df.shape

(10000, 11)

In [12]:
#Dropping all rows having missing records

df.dropna(inplace=True)
#verify
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [13]:
df.shape

(9969, 11)

In [14]:
df.dtypes

invoice_id          int64
Branch             object
City               object
category           object
unit_price         object
quantity          float64
date               object
time               object
payment_method     object
rating            float64
profit_margin     float64
dtype: object

In [15]:
#replace a $ sign in blank
df['unit_price']=(df['unit_price'].astype(str).str.replace('$', '',regex=False).str.strip().astype(float))

df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05-01-2019,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08-03-2019,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03-03-2019,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27-01-2019,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08-02-2019,10:37:00,Ewallet,5.3,0.48

In [16]:
df.dtypes

invoice_id          int64
Branch             object
City               object
category           object
unit_price        float64
quantity          float64
date               object
time               object
payment_method     object
rating            float64
profit_margin     float64
dtype: object

In [17]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='object')

In [18]:
df['total']=df['unit_price']*df['quantity']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05-01-2019,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08-03-2019,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03-03-2019,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27-01-2019,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08-02-2019,10:37:00,Ewallet,5.3,0.48,604.17

In [19]:
#total sales (revenue)
total_sales = df['total'].sum()
total_sales

np.float64(1209726.38)

In [20]:
#total profit
df['profit'] = df['total'] * df['profit_margin']
total_profit = df['profit'].sum()
total_profit

np.float64(476139.4257)

In [21]:
#average order value
average_order_value = df['total'].mean()
average_order_value

np.float64(121.34881933995385)

In [22]:
#total quantity Sold
total_quantity = df['quantity'].sum()
total_quantity

np.float64(23483.0)

In [23]:
#sales_by_Branch 
sales_by_Branch = (
    df
    .groupby('Branch')['total']
    .sum()
    .reset_index()
)
print(sales_by_Branch)

     Branch     total
0   WALM001  10225.68
1   WALM002   7734.12
2   WALM003  24950.56
3   WALM004   7565.65
4   WALM005  11654.64
..      ...       ...
95  WALM096  11256.17
96  WALM097   7376.91
97  WALM098   9509.93
98  WALM099  18074.60
99  WALM100   8254.34

[100 rows x 2 columns]

In [24]:
#sales_by_City
sales_by_City = (
    df
    .groupby('City')['total']
    .sum()
    .reset_index()
)
print(sales_by_City)

           City     total
0       Abilene   9377.82
1         Alamo   7531.35
2         Alice   7376.91
3         Allen   7688.50
4      Amarillo   6777.46
..          ...       ...
93     Victoria  16009.03
94         Waco  17640.17
95   Waxahachie  40703.33
96  Weatherford  18074.60
97      Weslaco  46351.79

[98 rows x 2 columns]

In [25]:
#sales_by_category
sales_by_category =(
    df
    .groupby('category')['total']
    .sum()
    .reset_index()
)
print(sales_by_category)

                 category      total
0  Electronic accessories   78175.03
1     Fashion accessories  489480.90
2      Food and beverages   53471.28
3       Health and beauty   46851.18
4      Home and lifestyle  489250.06
5       Sports and travel   52497.93

In [26]:
#profit_by_category
profit_by_category = (
        df
        .groupby('category')['profit']
        .sum() 
        .reset_index()
)
print(profit_by_category)

                 category       profit
0  Electronic accessories   30772.4895
1     Fashion accessories  192314.8932
2      Food and beverages   21552.8622
3       Health and beauty   18671.7345
4      Home and lifestyle  192213.6381
5       Sports and travel   20613.8082

In [27]:
# Best selling category
best_category = (
    df
    .groupby('category')['quantity']
    .sum()
    .sort_values(ascending=False)
)
best_category

category
Fashion accessories       9653.0
Home and lifestyle        9610.0
Electronic accessories    1494.0
Food and beverages         952.0
Sports and travel          920.0
Health and beauty          854.0
Name: quantity, dtype: float64

In [28]:
#paymentb method distribution
payment_kpi = (
    df['payment_method']
    .value_counts()
    .reset_index()
    .rename(columns={
        'index':'payment_method',
        'payment_method':
 'transactions'
    })
)

payment_kpi

  transactions  count
0  Credit card   4256
1      Ewallet   3881
2         Cash   1832

In [29]:
#average rating by category
avg_rating_category = (
    df
    .groupby('category',
as_index=False)['rating']
    .mean()
    .rename(columns={'rating':
'avr_rating'})
)

avg_rating_category

                 category  avr_rating
0  Electronic accessories    5.912172
1     Fashion accessories    5.782107
2      Food and beverages    7.113218
3       Health and beauty    7.003289
4      Home and lifestyle    5.739159
5       Sports and travel    6.916265

In [30]:
#sales trend by months

df['date'] = pd.to_datetime(df['date'],errors='coerce',dayfirst=True)

df['month']= df['date'].dt.to_period('M')

monthly_sales_trend = (
    df
    .groupby('month', as_index=False)
['total']
    .sum()
)

monthly_sales_trend['month'] = monthly_sales_trend['month'].astype(str)
monthly_sales_trend

top_5_months = (
    monthly_sales_trend
     .sort_values(by='total',
  ascending=False)
    .head(5)
)

top_5_months

      month      total
0   2019-01  110754.16
2   2019-03  104243.34
1   2019-02   92589.88
26  2021-12   66930.00
50  2023-12   66092.00

In [31]:
#peak sales trend
df['date'] = pd.to_datetime(df['date'])

df['hour'] = df['date'].dt.hour

hourly_sales_trend = (
    df
    .groupby('hour', as_index=False)
['total']
    .sum()
)

top_5_hours = (
hourly_sales_trend.sort_values(by='total',ascending=False).head(5)
)

print(top_5_hours)

   hour       total
0     0  1209726.38

In [32]:
!pip install mysql-connector-python pandas

Requirement already satisfied: mysql-connector-python in c:\users\user\anaconda3\lib\site-packages (9.5.0)
Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [33]:
!pip install pymysql pandas

Requirement already satisfied: pymysql in c:\users\user\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [34]:
import mysql.connector
import pandas as pd
from mysql.connector import Error

# Your database credentials
host = 'localhost' # or your server's IP address
user = 'root'
password = 'world'
database = 'walmart' # optional, can be specified later

try:
    # Establish the connection
    connection = mysql.connector.connect(
        host=host,
        user=user,
        passwd=password,
        database=database
    )
    if connection.is_connected():
        print("Connection to MySQL DB successful")
        # Create a cursor object
        cursor = connection.cursor()

except Error as e:
    print(f"Error while connecting to MySQL: {e}")

Connection to MySQL DB successful

In [37]:
query = "SELECT * FROM  walmart_clean_data";

    # Read data from MySQL into a pandas DataFrame
df = pd.read_sql(query, connection)

    # Display the first few rows of the DataFrame
print(df.head())

   invoice_id   Branch         City                category unit_price  \
0           1  WALM003  San Antonio       Health and beauty     $74.69
1           2  WALM048    Harlingen  Electronic accessories     $15.28
2           3  WALM067  Haltom City      Home and lifestyle     $46.33
3           4  WALM064      Bedford       Health and beauty     $58.22
4           5  WALM013       Irving       Sports and travel     $86.31

   quantity      date      time payment_method  rating  profit_margin
0       7.0  05/01/19  13:08:00        Ewallet     9.1           0.48
1       5.0  08/03/19  10:29:00           Cash     9.6           0.48
2       7.0  03/03/19  13:23:00    Credit card     7.4           0.33
3       8.0  27/01/19  20:33:00        Ewallet     8.4           0.33
4       7.0  08/02/19  10:37:00        Ewallet     5.3           0.48

C:\Users\User\AppData\Local\Temp\ipykernel_9628\1314530319.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

In [38]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
import mysql.connector

# Assuming your cleaned data is in a DataFrame named 'df_cleaned'

# Database connection details
db_user = 'root'
db_password = 'world'
db_host = 'localhost' # or your host IP
db_name = 'walmart'
table_name = 'walmart_clean_data' # The name for your new MySQL table

# Create the connection engine
try:
    engine = create_engine(f'mysql+mysqlconnector://{db_user}:{db_password}@{db_host}/{db_name}')

    # Transfer the DataFrame to MySQL
    # if_exists='replace' will drop the table if it exists and create a new one
    # if_exists='append' will add rows to an existing table
    df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

    print(f"Successfully transferred data to table '{table_name}' in '{db_name}'.")

except Exception as e:
    print(f"An error occurred: {e}")
finally:
    if 'engine' in locals() and engine is not None:
        engine.dispose()